sequenceDiagram
    participant User
    participant Front as Frontend
    participant API
    participant DB
    
    User->>Front: Start Quiz
    Front->>API: POST /api/learning/{mod}/quiz/start
    API->>DB: Create QuizAttempt
    API-->>Front: Return Question IDs & Text
    User->>Front: Submits Answers
    Front->>API: POST /api/learning/quiz/submit
    API->>DB: Evaluate & Update QuizAttempt
    API-->>Front: Score & Explanations\n